version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4467:4467"
    environment:
      PRISMA_CONFIG: |
        port: 4467
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-34-234-228-127.compute-1.amazonaws.com
            database: d30pqcui4dqj5j
            user: gzdyiyphgdpyct
            password: 472db1cd3f72e164a1541f77eb48a8b66cff260f3abcb9a73650f3aa92fa8609
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true